version: '3.7'

networks:
  webservice_network:
    driver: bridge

services:

  django:
    image: devroastproject
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      [webservice_network]
    env_file:
      - devroast/.env
    depends_on:
      - postgres

  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      [webservice_network]
    env_file:
      - devroast/.env
    depends_on:
      - postgres
      - django
    volumes:
      - type: bind
        source: ./frontend/react-frontend
        target: /app
      - '/app/node_modules'

  postgres:
    image: postgres:12.2-alpine
    networks:
      [webservice_network]
    volumes:
      - devroast:/var/lib/postgresql/data/
    ports:
      - 543:5432
    env_file:
      - devroast/.env

  redis:
    image: redis:5.0.3-alpine
    networks:
      [webservice_network]
    dns:
      - 8.8.8.8

volumes: 
  devroast:
